[package]
name = "rust_test"
version = "0.1.0"
authors = ["Sujay Jayakar <sujayakar@dropbox.com>"]

build = "build.rs"
[build-dependencies]
gcc = "0.3.17"

[dependencies]
backtrace = "0.2.3"
lazy_static = "0.1.*"